from flask import Flask, request, jsonify
from google import genai
from google.genai import types
from PIL import Image
from io import BytesIO
import base64

app = Flask(__name__)

# ── Gemini Client ──────────────────────────────────────────────────────────────
API_KEY = "AQ.Ab8RN6LGigfjVqrpmHgd59Yo4BLpYk-jbFaJg-BlYWOrAWC7Dw"
client = genai.Client(api_key=API_KEY)

# ── CORS ───────────────────────────────────────────────────────────────────────
@app.after_request
def add_cors(response):
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    response.headers["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
    return response

@app.route("/generate-image", methods=["OPTIONS"])
def preflight():
    return "", 204

# ── Health check ───────────────────────────────────────────────────────────────
@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "online", "model": "gemini-2.0-flash-preview-image-generation"})

# ── POST /generate-image ───────────────────────────────────────────────────────
@app.route("/generate-image", methods=["POST"])
def generate_image():
    try:
        data = request.get_json()

        if not data or "prompt" not in data:
            return jsonify({"error": "Prompt is required"}), 400

        prompt = data["prompt"]
        print(f"\n[Gemini Flask] Generating image for: {prompt[:100]}...")

        # Call Gemini with IMAGE response modality (correct SDK syntax)
        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["TEXT", "IMAGE"]
            )
        )

        # Loop through parts — find the inline image data
        for part in response.candidates[0].content.parts:
            if hasattr(part, "inline_data") and part.inline_data is not None:
                image_bytes = part.inline_data.data
                mime_type = part.inline_data.mime_type or "image/png"

                # Verify valid image with Pillow
                image = Image.open(BytesIO(image_bytes))
                print(f"[Gemini Flask] ✅ Image ready: {image.size}px, mode={image.mode}")

                # Convert to base64
                image_base64 = base64.b64encode(image_bytes).decode("utf-8")

                return jsonify({
                    "success": True,
                    "imageUrl": f"data:{mime_type};base64,{image_base64}",
                    "width": image.size[0],
                    "height": image.size[1]
                })

        print("[Gemini Flask] ⚠️ No inline image in response.")
        return jsonify({"success": False, "error": "No image generated by Gemini"}), 500

    except Exception as e:
        print(f"[Gemini Flask] ❌ Error: {str(e)}")
        return jsonify({"success": False, "error": str(e)}), 500


if __name__ == "__main__":
    print("=" * 60)
    print("  OMNIAI Gemini Image Generation Server")
    print("  Model : gemini-2.5-flash-image")
    print("  URL   : http://localhost:5005")
    print("=" * 60)
    app.run(host="0.0.0.0", port=5005, debug=False)
